import jsPDF from 'jspdf';

// Helper function to format dates
const formatDate = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
};

/**
 * Generates a PDF report for user information
 * @param {Object} userData - User data object
 * @returns {jsPDF} - Generated PDF document
 */
export const generateUserReportPDF = (userData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  let yPosition = 20;

  // Company Header
  doc.setFillColor(41, 128, 185);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  // Add company logo
  try {
    const logoImg = new Image();
    logoImg.src = '/logo.png';
    doc.addImage(logoImg, 'PNG', 20, 8, 20, 20);
  } catch (error) {
    console.log('Logo not loaded, using text fallback');
  }
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('SwiftRide', pageWidth / 2, 18, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text('User Information Report', pageWidth / 2, 28, { align: 'center' });
  
  yPosition = 50;
  doc.setTextColor(0, 0, 0);

  // Report Details
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Details:', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const reportId = `USR-${Date.now().toString().slice(-6)}`;
  const generatedDate = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  
  doc.text(`Report ID: ${reportId}`, 20, yPosition);
  doc.text(`Generated: ${generatedDate}`, 20, yPosition + 5);
  doc.text(`Report Type: User Information`, 20, yPosition + 10);
  doc.text(`User ID: ${userData._id}`, 20, yPosition + 15);
  
  yPosition += 35;

  // User Information Box
  doc.setFillColor(240, 248, 255);
  doc.rect(15, yPosition - 5, pageWidth - 30, 60, 'F');
  doc.setDrawColor(41, 128, 185);
  doc.rect(15, yPosition - 5, pageWidth - 30, 60, 'S');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('User Information', 20, yPosition);
  yPosition += 15;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  // Basic Information
  doc.text(`Name: ${userData.name}`, 20, yPosition);
  doc.text(`Email: ${userData.email}`, 20, yPosition + 5);
  doc.text(`Phone: ${userData.phone || 'Not provided'}`, 20, yPosition + 10);
  doc.text(`Role: ${userData.role}`, 20, yPosition + 15);
  doc.text(`Status: ${userData.isActive ? 'Active' : 'Inactive'}`, 20, yPosition + 20);
  doc.text(`Joined: ${formatDate(userData.createdAt)}`, 20, yPosition + 25);
  
  yPosition += 40;

  // Additional Information
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Additional Information', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  if (userData.address) {
    doc.text(`Address: ${userData.address}`, 20, yPosition);
    yPosition += 5;
  }
  
  if (userData.licenseNumber) {
    doc.text(`License Number: ${userData.licenseNumber}`, 20, yPosition);
    yPosition += 5;
  }
  
  if (userData.branchLocation) {
    doc.text(`Branch Location: ${userData.branchLocation}`, 20, yPosition);
    yPosition += 5;
  }

  // Account Statistics
  yPosition += 10;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Account Statistics', 20, yPosition);
  yPosition += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Account Created: ${formatDate(userData.createdAt)}`, 20, yPosition);
  doc.text(`Last Updated: ${formatDate(userData.updatedAt)}`, 20, yPosition + 5);
  doc.text(`Account Age: ${Math.floor((new Date() - new Date(userData.createdAt)) / (1000 * 60 * 60 * 24))} days`, 20, yPosition + 10);

  // Footer
  yPosition = pageHeight - 30;
  doc.setFillColor(41, 128, 185);
  doc.rect(0, yPosition, pageWidth, 30, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by SwiftRide', pageWidth / 2, yPosition + 10, { align: 'center' });
  doc.text(`Report ID: ${reportId} | Page 1 of 1`, pageWidth / 2, yPosition + 20, { align: 'center' });

  return doc;
};

/**
 * Exports user data as PDF and triggers download
 * @param {Object} userData - User data object
 * @param {Function} enqueueSnackbar - Snackbar notification function
 */
export const exportUserPDF = (userData, enqueueSnackbar) => {
  try {
    const doc = generateUserReportPDF(userData);
    const filename = `user-report-${userData.name.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`;
    doc.save(filename);
    enqueueSnackbar(`User report exported: ${filename}`, { variant: 'success' });
  } catch (error) {
    console.error('Error exporting user PDF:', error);
    enqueueSnackbar('Error exporting user report', { variant: 'error' });
  }
};
